# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/CyclomaticComplexity:
  Max: 22
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 22
Style/MultilineTernaryOperator:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
