assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
  s3cfg: yegor256/home#assets/s3cfg
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo apt-get -y update
  sudo gem install pdd -v 0.20.5
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/rumble/version.rb
    git add lib/rumble/version.rb
    git commit -m "version set to ${tag}"
    gem build rumble.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  script: |-
    bundle install
    rake
    pdd
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
